### ISSUE TITLE
homework#4

### ISSUE THREAD

**Issue by denisskin** [dslmnvv/todo_list#6]
**Чистота кода и общая структура проекта (5/5)**
- Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (+1)
- Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (+1)
- Форматирование кода присутствует (+1)
- Код разбит на фичи и слои (не важно, feature-first / layer-first) (+2)

**Навигация, UI, animations (8/8)**
- Навигация инкапсулирована в отдельной сущности, отсутствуют явные переходы Navigator.push прямо в колбеках (+1)
- Текст длинных заметок обрезается по макету (+1)
- Поддержка ночной темы (+1)
- Реализованы анимации для добавления/исчезновения/редактирования и прочих взаимодействий с заметками (+1 балл)
- Реализована поддержка лендскейп-ориентации (+2 балла)
- Реализована поддержка больших экранов (планшеты) (+2 балла)

**Firebase (3/3)**
- Реализована работа с Remote Configs, работает рантайм-переключение цвета важности (дефолтный красный по Фигме vs #793cd8) (+2)
- К проекту подключён и настроен Firebase Crashlytics, репортинг ошибок работает (+1)

**Build & Release (4/8)**
- Поддержаны 2 флейвора: для сборки тестинг и прод окружения.   (+2)
- Настроен CI на GitHub (+1 балл за каждый шаг (форматирование, линтер, тесты, сборка, деплой))  (+0/4)
- Есть распространение через какой-то сервис вроде Firebase App Distribution (+2)

**Разное (2/2)**
- Добавлен инструмент для аналитики: Firebase/AppMetrica. Собирается аналитика по событиям: добавление, удаление, выполнение, переходы по экранам (+1)
- Для дата-моделей используется пакет freezed (+1)

**Comment by dslmnvv** [comment]
> **Чистота кода и общая структура проекта (5/5)**
> 
> * Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (+1)
> * Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил (+1)
> * Форматирование кода присутствует (+1)
> * Код разбит на фичи и слои (не важно, feature-first / layer-first) (+2)
> 
> **Навигация, UI, animations (8/8)**
> 
> * Навигация инкапсулирована в отдельной сущности, отсутствуют явные переходы Navigator.push прямо в колбеках (+1)
> * Текст длинных заметок обрезается по макету (+1)
> * Поддержка ночной темы (+1)
> * Реализованы анимации для добавления/исчезновения/редактирования и прочих взаимодействий с заметками (+1 балл)
> * Реализована поддержка лендскейп-ориентации (+2 балла)
> * Реализована поддержка больших экранов (планшеты) (+2 балла)
> 
> **Firebase (3/3)**
> 
> * Реализована работа с Remote Configs, работает рантайм-переключение цвета важности (дефолтный красный по Фигме vs #793cd8) (+2)
> * К проекту подключён и настроен Firebase Crashlytics, репортинг ошибок работает (+1)
> 
> **Build & Release (4/8)**
> 
> * Поддержаны 2 флейвора: для сборки тестинг и прод окружения.   (+2)
> * Настроен CI на GitHub (+1 балл за каждый шаг (форматирование, линтер, тесты, сборка, деплой))  (+0/4)
> * Есть распространение через какой-то сервис вроде Firebase App Distribution (+2)
> 
> **Разное (2/2)**
> 
> * Добавлен инструмент для аналитики: Firebase/AppMetrica. Собирается аналитика по событиям: добавление, удаление, выполнение, переходы по экранам (+1)
> * Для дата-моделей используется пакет freezed (+1)

Спасибо за оценку
CI настроен, просто не стопорится на этапе форматирования, как это пофиксить я пока не понял
